module.exports = {
  docs: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        {
          type: 'autogenerated',
          dirName: 'getting-started',
        }
      ],
    },
    {
      type: 'category',
      label: 'Tools in Mod Toolkit',
      items: [
        {
          type: 'autogenerated',
          dirName: 'tools-in-mtk',
        }
      ],
    },
    {
      type: 'category',
      label: 'Mod Types',
      items: [
        {
          type: 'autogenerated',
          dirName: 'support-mod-types',
        }
      ],
    },
    {
      type: 'category',
      label: 'LuaScript',
      items: [
        {
          type: 'autogenerated',
          dirName: 'LuaScript',
        }
      ],
    },
    {
      type: 'category',
      label: 'Details',
      items: [
        {
          type: 'autogenerated',
          dirName: 'details',
        }
      ],
    },      
    {
      type: 'category',
      label: 'Complete Scripts',
      items: [
        {
          type: 'autogenerated',
          dirName: 'complete-scripts',
        }
      ],
    },
    {
      type: 'category',
      label: 'Projects',
      items: [
        {
          type: 'autogenerated',
          dirName: 'projects',
        }
      ],
    },
    {
      type: 'category',
      label: 'Common Issues',
      items: [
        {
          type: 'autogenerated',
          dirName: 'common-issues',
        }
      ],
    },
  ],
};
