module.exports = {
  docs: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        {
          type: 'autogenerated',
          dirName: 'getting-started',
        }
      ],
    },
    {
      type: 'category',
      label: 'Tutorials',
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorials',
        }
      ],
    },    
    {
      type: 'category',
      label: 'Details',
      items: [
        {
          type: 'autogenerated',
          dirName: 'details',
        }
      ],
    },      
    {
      type: 'category',
      label: 'Snippets',
      items: [
        {
          type: 'autogenerated',
          dirName: 'snippets',
        }
      ],
    },
    {
      type: 'category',
      label: 'Complete Scripts',
      items: [
        {
          type: 'autogenerated',
          dirName: 'complete-scripts',
        }
      ],
    },
    {
      type: 'category',
      label: 'Projects',
      items: [
        {
          type: 'autogenerated',
          dirName: 'projects',
        }
      ],
    },
  ],
};
